services:
  php:
    build: .
    container_name: ecoride-php
    volumes:
      - ./app:/var/www/app
      - ./public:/var/www/public
      - ./config:/var/www/config
      - ./sessions:/tmp/sessions
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: EcoRide
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: ecoridepass
      MONGODB_URI: mongodb://ecoride:ecoride123@mongo:27017/admin
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks: [ ecoride-network ]

  nginx:
    image: nginx:latest
    container_name: ecoride-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_started   # no php healthcheck; just wait for it to start
    networks: [ ecoride-network ]

  mysql:
    image: mysql:8.0
    container_name: ecoride-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: Ecoride
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: ecoridepass
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 30s
    networks: [ ecoride-network ]

  mongo:
    image: mongo:4.4
    container_name: ecoride-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ecoride
      MONGO_INITDB_ROOT_PASSWORD: ecoride123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongo --username $${MONGO_INITDB_ROOT_USERNAME} --password $${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval 'db.adminCommand({ping:1})' >/dev/null 2>&1"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
    networks: [ ecoride-network ]

volumes:
  mysql-data:
    driver: local
  mongo-data:
    driver: local

networks:
  ecoride-network:
    driver: bridge